# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_dialog(object):
    def setupUi(self, menu_dialog):
        menu_dialog.setObjectName("menu_dialog")
        menu_dialog.resize(865, 572)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(menu_dialog.sizePolicy().hasHeightForWidth())
        menu_dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(menu_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.table_item_list = QtWidgets.QTableWidget(menu_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_item_list.sizePolicy().hasHeightForWidth())
        self.table_item_list.setSizePolicy(sizePolicy)
        self.table_item_list.setObjectName("table_item_list")
        self.table_item_list.setColumnCount(6)
        self.table_item_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_item_list.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.table_item_list, 8, 0, 1, 4)
        self.label = QtWidgets.QLabel(menu_dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_drinks = QtWidgets.QPushButton(menu_dialog)
        self.btn_drinks.setObjectName("btn_drinks")
        self.horizontalLayout_2.addWidget(self.btn_drinks)
        self.btn_food = QtWidgets.QPushButton(menu_dialog)
        self.btn_food.setObjectName("btn_food")
        self.horizontalLayout_2.addWidget(self.btn_food)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_order_list = QtWidgets.QTableWidget(menu_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_order_list.sizePolicy().hasHeightForWidth())
        self.table_order_list.setSizePolicy(sizePolicy)
        self.table_order_list.setObjectName("table_order_list")
        self.table_order_list.setColumnCount(3)
        self.table_order_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_list.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table_order_list)
        self.label_result = QtWidgets.QLabel(menu_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.label_result_under_order_table = QtWidgets.QLabel(menu_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_under_order_table.sizePolicy().hasHeightForWidth())
        self.label_result_under_order_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_result_under_order_table.setFont(font)
        self.label_result_under_order_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_result_under_order_table.setText("")
        self.label_result_under_order_table.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_under_order_table.setObjectName("label_result_under_order_table")
        self.verticalLayout.addWidget(self.label_result_under_order_table)
        self.btn_order_items = QtWidgets.QPushButton(menu_dialog)
        self.btn_order_items.setObjectName("btn_order_items")
        self.verticalLayout.addWidget(self.btn_order_items)
        self.btn_menu_cancel = QtWidgets.QPushButton(menu_dialog)
        self.btn_menu_cancel.setObjectName("btn_menu_cancel")
        self.verticalLayout.addWidget(self.btn_menu_cancel)
        self.gridLayout.addLayout(self.verticalLayout, 8, 4, 1, 2)
        self.label_final_price = QtWidgets.QLabel(menu_dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_final_price.setFont(font)
        self.label_final_price.setText("")
        self.label_final_price.setObjectName("label_final_price")
        self.gridLayout.addWidget(self.label_final_price, 1, 5, 1, 1)

        self.retranslateUi(menu_dialog)
        QtCore.QMetaObject.connectSlotsByName(menu_dialog)

    def retranslateUi(self, menu_dialog):
        _translate = QtCore.QCoreApplication.translate
        menu_dialog.setWindowTitle(_translate("menu_dialog", "Menü"))
        item = self.table_item_list.horizontalHeaderItem(0)
        item.setText(_translate("menu_dialog", "ID"))
        item = self.table_item_list.horizontalHeaderItem(1)
        item.setText(_translate("menu_dialog", "Név"))
        item = self.table_item_list.horizontalHeaderItem(2)
        item.setText(_translate("menu_dialog", "Leírás"))
        item = self.table_item_list.horizontalHeaderItem(3)
        item.setText(_translate("menu_dialog", "Kategória"))
        item = self.table_item_list.horizontalHeaderItem(4)
        item.setText(_translate("menu_dialog", "Kiszerelés"))
        item = self.table_item_list.horizontalHeaderItem(5)
        item.setText(_translate("menu_dialog", "Ár"))
        self.label.setText(_translate("menu_dialog", "Végösszeg:"))
        self.btn_drinks.setText(_translate("menu_dialog", "Italok"))
        self.btn_food.setText(_translate("menu_dialog", "Ételek"))
        item = self.table_order_list.horizontalHeaderItem(0)
        item.setText(_translate("menu_dialog", "Név"))
        item = self.table_order_list.horizontalHeaderItem(1)
        item.setText(_translate("menu_dialog", "Darab"))
        item = self.table_order_list.horizontalHeaderItem(2)
        item.setText(_translate("menu_dialog", "Ár"))
        self.btn_order_items.setText(_translate("menu_dialog", "Megrendel"))
        self.btn_menu_cancel.setText(_translate("menu_dialog", "Kilép"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_dialog = QtWidgets.QDialog()
    ui = Ui_menu_dialog()
    ui.setupUi(menu_dialog)
    menu_dialog.show()
    sys.exit(app.exec_())
