# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_server_window(object):
    def setupUi(self, server_window):
        server_window.setObjectName("server_window")
        server_window.resize(804, 560)
        self.gridLayout = QtWidgets.QGridLayout(server_window)
        self.gridLayout.setObjectName("gridLayout")
        self.server_tabwidget = QtWidgets.QTabWidget(server_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_tabwidget.sizePolicy().hasHeightForWidth())
        self.server_tabwidget.setSizePolicy(sizePolicy)
        self.server_tabwidget.setObjectName("server_tabwidget")
        self.tab_orders = QtWidgets.QWidget()
        self.tab_orders.setObjectName("tab_orders")
        self.table_orders = QtWidgets.QTableWidget(self.tab_orders)
        self.table_orders.setGeometry(QtCore.QRect(20, 10, 751, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_orders.sizePolicy().hasHeightForWidth())
        self.table_orders.setSizePolicy(sizePolicy)
        self.table_orders.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_orders.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_orders.setObjectName("table_orders")
        self.table_orders.setColumnCount(6)
        self.table_orders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orders.setHorizontalHeaderItem(5, item)
        self.server_tabwidget.addTab(self.tab_orders, "")
        self.tab_payment = QtWidgets.QWidget()
        self.tab_payment.setObjectName("tab_payment")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_payment)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 751, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_order_delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_order_delete.setObjectName("btn_order_delete")
        self.verticalLayout_2.addWidget(self.btn_order_delete)
        self.btn_paid = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_paid.setObjectName("btn_paid")
        self.verticalLayout_2.addWidget(self.btn_paid)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 13, 1, 1, 1)
        self.label_order_id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_order_id.setObjectName("label_order_id")
        self.gridLayout_2.addWidget(self.label_order_id, 4, 1, 1, 1)
        self.label_order_time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_order_time.setObjectName("label_order_time")
        self.gridLayout_2.addWidget(self.label_order_time, 10, 1, 1, 1)
        self.label_actual_time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_actual_time.setObjectName("label_actual_time")
        self.gridLayout_2.addWidget(self.label_actual_time, 12, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_order_status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_order_status.setObjectName("label_order_status")
        self.gridLayout_2.addWidget(self.label_order_status, 6, 1, 1, 1)
        self.label_result = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_result.setObjectName("label_result")
        self.gridLayout_2.addWidget(self.label_result, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 11, 1, 1, 1)
        self.table_order_details = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_order_details.sizePolicy().hasHeightForWidth())
        self.table_order_details.setSizePolicy(sizePolicy)
        self.table_order_details.setObjectName("table_order_details")
        self.table_order_details.setColumnCount(3)
        self.table_order_details.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_details.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_details.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order_details.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.table_order_details, 0, 0, 14, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.server_tabwidget.addTab(self.tab_payment, "")
        self.tab_full_supply = QtWidgets.QWidget()
        self.tab_full_supply.setObjectName("tab_full_supply")
        self.all_items_tab = QtWidgets.QTabWidget(self.tab_full_supply)
        self.all_items_tab.setGeometry(QtCore.QRect(20, 10, 671, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_items_tab.sizePolicy().hasHeightForWidth())
        self.all_items_tab.setSizePolicy(sizePolicy)
        self.all_items_tab.setObjectName("all_items_tab")
        self.tab_soup = QtWidgets.QWidget()
        self.tab_soup.setObjectName("tab_soup")
        self.table_soup_list = QtWidgets.QTableWidget(self.tab_soup)
        self.table_soup_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_soup_list.setObjectName("table_soup_list")
        self.table_soup_list.setColumnCount(6)
        self.table_soup_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soup_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_soup, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.table_salad_list = QtWidgets.QTableWidget(self.tab_2)
        self.table_salad_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_salad_list.setObjectName("table_salad_list")
        self.table_salad_list.setColumnCount(6)
        self.table_salad_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_salad_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_2, "")
        self.tab_sultek = QtWidgets.QWidget()
        self.tab_sultek.setObjectName("tab_sultek")
        self.table_meat_list = QtWidgets.QTableWidget(self.tab_sultek)
        self.table_meat_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_meat_list.setObjectName("table_meat_list")
        self.table_meat_list.setColumnCount(6)
        self.table_meat_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_meat_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_sultek, "")
        self.tab_fish_main = QtWidgets.QWidget()
        self.tab_fish_main.setObjectName("tab_fish_main")
        self.table_fishfood_list = QtWidgets.QTableWidget(self.tab_fish_main)
        self.table_fishfood_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_fishfood_list.setObjectName("table_fishfood_list")
        self.table_fishfood_list.setColumnCount(6)
        self.table_fishfood_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fishfood_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_fish_main, "")
        self.tab_desserts = QtWidgets.QWidget()
        self.tab_desserts.setObjectName("tab_desserts")
        self.table_dessert_list = QtWidgets.QTableWidget(self.tab_desserts)
        self.table_dessert_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_dessert_list.setObjectName("table_dessert_list")
        self.table_dessert_list.setColumnCount(6)
        self.table_dessert_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dessert_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_desserts, "")
        self.tab_coffee_tee = QtWidgets.QWidget()
        self.tab_coffee_tee.setObjectName("tab_coffee_tee")
        self.table_coffee_tee_list = QtWidgets.QTableWidget(self.tab_coffee_tee)
        self.table_coffee_tee_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_coffee_tee_list.setObjectName("table_coffee_tee_list")
        self.table_coffee_tee_list.setColumnCount(6)
        self.table_coffee_tee_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee_tee_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_coffee_tee, "")
        self.tab_soft_drinks = QtWidgets.QWidget()
        self.tab_soft_drinks.setObjectName("tab_soft_drinks")
        self.table_soft_drinks_list = QtWidgets.QTableWidget(self.tab_soft_drinks)
        self.table_soft_drinks_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_soft_drinks_list.setObjectName("table_soft_drinks_list")
        self.table_soft_drinks_list.setColumnCount(6)
        self.table_soft_drinks_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_soft_drinks_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_soft_drinks, "")
        self.tab_beer = QtWidgets.QWidget()
        self.tab_beer.setObjectName("tab_beer")
        self.table_beer_list = QtWidgets.QTableWidget(self.tab_beer)
        self.table_beer_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_beer_list.setObjectName("table_beer_list")
        self.table_beer_list.setColumnCount(6)
        self.table_beer_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_beer_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_beer, "")
        self.tab_wein = QtWidgets.QWidget()
        self.tab_wein.setObjectName("tab_wein")
        self.table_wein_list = QtWidgets.QTableWidget(self.tab_wein)
        self.table_wein_list.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.table_wein_list.setObjectName("table_wein_list")
        self.table_wein_list.setColumnCount(6)
        self.table_wein_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_wein_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_wein, "")
        self.tab_shoots = QtWidgets.QWidget()
        self.tab_shoots.setObjectName("tab_shoots")
        self.table_shoot_list = QtWidgets.QTableWidget(self.tab_shoots)
        self.table_shoot_list.setGeometry(QtCore.QRect(10, 10, 641, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_shoot_list.sizePolicy().hasHeightForWidth())
        self.table_shoot_list.setSizePolicy(sizePolicy)
        self.table_shoot_list.setObjectName("table_shoot_list")
        self.table_shoot_list.setColumnCount(6)
        self.table_shoot_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_shoot_list.setHorizontalHeaderItem(5, item)
        self.all_items_tab.addTab(self.tab_shoots, "")
        self.server_tabwidget.addTab(self.tab_full_supply, "")
        self.tab_edit_supply = QtWidgets.QWidget()
        self.tab_edit_supply.setObjectName("tab_edit_supply")
        self.groupBox = QtWidgets.QGroupBox(self.tab_edit_supply)
        self.groupBox.setGeometry(QtCore.QRect(60, 40, 291, 431))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_item_types = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_item_types.setObjectName("comboBox_item_types")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_item_types)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_item_category = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_item_category.setObjectName("comboBox_item_category")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_item_category)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_items = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_items.setObjectName("comboBox_items")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_items)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 190, 271, 231))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_item_name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_item_name.setObjectName("lineEdit_item_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_item_name)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_item_unitprice = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_item_unitprice.setObjectName("lineEdit_item_unitprice")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_item_unitprice)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_item_discount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_item_discount.setObjectName("lineEdit_item_discount")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_item_discount)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_selected_item_category = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_selected_item_category.setObjectName("comboBox_selected_item_category")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_selected_item_category)
        self.lineEdit_description = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_description)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_edit_supply)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 40, 311, 431))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 271, 241))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_new_item_name = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_new_item_name.setObjectName("lineEdit_new_item_name")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_new_item_name)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_new_item_unitprice = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_new_item_unitprice.setObjectName("lineEdit_new_item_unitprice")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_new_item_unitprice)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_new_item_discount = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_new_item_discount.setObjectName("lineEdit_new_item_discount")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_new_item_discount)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.comboBox_new_item_category = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_new_item_category.setObjectName("comboBox_new_item_category")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_new_item_category)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.comboBox_new_item_type = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_new_item_type.setObjectName("comboBox_new_item_type")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_new_item_type)
        self.lineEdit_new_item_description = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_new_item_description.setObjectName("lineEdit_new_item_description")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_new_item_description)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 309, 291, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_save_new_item = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save_new_item.setObjectName("btn_save_new_item")
        self.verticalLayout.addWidget(self.btn_save_new_item)
        self.btn_save_modification = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_save_modification.setObjectName("btn_save_modification")
        self.verticalLayout.addWidget(self.btn_save_modification)
        self.server_tabwidget.addTab(self.tab_edit_supply, "")
        self.gridLayout.addWidget(self.server_tabwidget, 0, 1, 1, 1)

        self.retranslateUi(server_window)
        self.server_tabwidget.setCurrentIndex(3)
        self.all_items_tab.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(server_window)

    def retranslateUi(self, server_window):
        _translate = QtCore.QCoreApplication.translate
        server_window.setWindowTitle(_translate("server_window", "RMSystem - server view"))
        item = self.table_orders.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Rendelés azonosító"))
        item = self.table_orders.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Kezdés"))
        item = self.table_orders.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Befejezés"))
        item = self.table_orders.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Összeg"))
        item = self.table_orders.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Állapot"))
        item = self.table_orders.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Fizetés"))
        self.server_tabwidget.setTabText(self.server_tabwidget.indexOf(self.tab_orders),
                                         _translate("server_window", "Rendelések"))
        self.server_tabwidget.setTabToolTip(self.server_tabwidget.indexOf(self.tab_orders),
                                            _translate("server_window", "Aktuális megrendelések"))
        self.btn_order_delete.setText(_translate("server_window", "Rendelés törlés"))
        self.btn_paid.setText(_translate("server_window", "Fizetve"))
        self.label_order_id.setText(_translate("server_window", "(rendelés azonosító)"))
        self.label_order_time.setText(_translate("server_window", "(rendelési idő)"))
        self.label_actual_time.setText(_translate("server_window", "(aktuális idő)"))
        self.label_6.setText(_translate("server_window", "Állapot:"))
        self.label_7.setText(_translate("server_window", "Összeg:"))
        self.label_order_status.setText(_translate("server_window", "(rendelés állapot)"))
        self.label_result.setText(_translate("server_window", "(összeg)"))
        self.label_5.setText(_translate("server_window", "Rendelés leadás ideje:"))
        self.label.setText(_translate("server_window", "Jelenleg idő:"))
        item = self.table_order_details.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Mennyiség"))
        item = self.table_order_details.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_order_details.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Ár"))
        self.label_2.setText(_translate("server_window", "Rendelés azonosító:"))
        self.server_tabwidget.setTabText(self.server_tabwidget.indexOf(self.tab_payment),
                                         _translate("server_window", "Fizetés"))
        self.server_tabwidget.setTabToolTip(self.server_tabwidget.indexOf(self.tab_payment), _translate("server_window",
                                                                                                        "Kiválasztott asztal rendelésének megtekintése"))
        item = self.table_soup_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_soup_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_soup_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_soup_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_soup_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_soup_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_soup), _translate("server_window", "Levesek"))
        item = self.table_salad_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_salad_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_salad_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_salad_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_salad_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_salad_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_2), _translate("server_window", "Saláták"))
        item = self.table_meat_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_meat_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_meat_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_meat_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_meat_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_meat_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_sultek),
                                      _translate("server_window", "Sültek"))
        item = self.table_fishfood_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_fishfood_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_fishfood_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_fishfood_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_fishfood_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_fishfood_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_fish_main),
                                      _translate("server_window", "Halételek"))
        item = self.table_dessert_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_dessert_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_dessert_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_dessert_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_dessert_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_dessert_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_desserts),
                                      _translate("server_window", "Desszertek"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_coffee_tee_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_coffee_tee),
                                      _translate("server_window", "Kávék / Teák"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_soft_drinks_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_soft_drinks),
                                      _translate("server_window", "Üditők"))
        item = self.table_beer_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_beer_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_beer_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_beer_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_beer_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_beer_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_beer), _translate("server_window", "Sörök"))
        item = self.table_wein_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_wein_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_wein_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_wein_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_wein_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_wein_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_wein), _translate("server_window", "Borok"))
        item = self.table_shoot_list.horizontalHeaderItem(0)
        item.setText(_translate("server_window", "Azonosító"))
        item = self.table_shoot_list.horizontalHeaderItem(1)
        item.setText(_translate("server_window", "Név"))
        item = self.table_shoot_list.horizontalHeaderItem(2)
        item.setText(_translate("server_window", "Leírás"))
        item = self.table_shoot_list.horizontalHeaderItem(3)
        item.setText(_translate("server_window", "Ár"))
        item = self.table_shoot_list.horizontalHeaderItem(4)
        item.setText(_translate("server_window", "Kategória"))
        item = self.table_shoot_list.horizontalHeaderItem(5)
        item.setText(_translate("server_window", "Kedvezmény"))
        self.all_items_tab.setTabText(self.all_items_tab.indexOf(self.tab_shoots),
                                      _translate("server_window", "Tömények"))
        self.server_tabwidget.setTabText(self.server_tabwidget.indexOf(self.tab_full_supply),
                                         _translate("server_window", "Teljes kínálat"))
        self.server_tabwidget.setTabToolTip(self.server_tabwidget.indexOf(self.tab_full_supply),
                                            _translate("server_window", "Teljes étlap és itallap áttekintése"))
        self.groupBox.setTitle(_translate("server_window", "Termék módosítás"))
        self.label_3.setText(_translate("server_window", "Termék típus:"))
        self.label_4.setText(_translate("server_window", "Termék kategória:"))
        self.label_8.setText(_translate("server_window", "Termékek:"))
        self.label_9.setText(_translate("server_window", "Termék név:"))
        self.label_10.setText(_translate("server_window", "Leírás:"))
        self.label_11.setText(_translate("server_window", "Egységár:"))
        self.label_12.setText(_translate("server_window", "Kedvezmény:"))
        self.label_13.setText(_translate("server_window", "Termék kategória:"))
        self.groupBox_2.setTitle(_translate("server_window", "Új termék"))
        self.label_14.setText(_translate("server_window", "Termék név:"))
        self.label_15.setText(_translate("server_window", "Leírás:"))
        self.label_16.setText(_translate("server_window", "Egységár:"))
        self.label_17.setText(_translate("server_window", "Kedvezmény:"))
        self.label_18.setText(_translate("server_window", "Termék kategória:"))
        self.label_19.setText(_translate("server_window", "Termék típus:"))
        self.btn_save_new_item.setText(_translate("server_window", "Új termék mentése"))
        self.btn_save_modification.setText(_translate("server_window", "Meglévő termék változtatásának mentése"))
        self.server_tabwidget.setTabText(self.server_tabwidget.indexOf(self.tab_edit_supply),
                                         _translate("server_window", "Kínálat szerkesztése"))
        self.server_tabwidget.setTabToolTip(self.server_tabwidget.indexOf(self.tab_edit_supply),
                                            _translate("server_window",
                                                       "Kínalt szerkesztése (új hozzáadása, törlése, szerkesztése)"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    server_window = QtWidgets.QDialog()
    ui = Ui_server_window()
    ui.setupUi(server_window)
    server_window.show()
    sys.exit(app.exec_())
